VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IControladorListadeIntimacoes"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Property Get ChromeIntimacoes() As Variant

End Property

Public Function PegarListaIntimacoes(Optional periodo As PeriodoDeTempo = Nothing, Optional Comarca As String = "") As Collection

End Function

Public Function PegarComarcasDisponiveis(nomeCaixaAColetar As String) As Collection

End Function
