VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IControladorEntradaCadastro"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Function PegarObjetoComNumeroProcesso() As Object

End Function

Public Function PegarNumeroProcessoDoObjetoToken(objToken As Object) As String

End Function

Public Sub MarcarAndamentoCadastrado(tokenNumeroProcesso As Object)

End Sub

Public Function ConfirmarEPegarInformacoesFinais(andamento As andamento, infoListas As StructInformacoesParaInterface) As StructInformacoesAndamento

End Function
